//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUI_Enforcer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FUI_Enforcer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string DialogAllFiles {
            get {
                return ResourceManager.GetString("DialogAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcting color.
        /// </summary>
        internal static string DialogCorrectColor {
            get {
                return ResourceManager.GetString("DialogCorrectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DialogError {
            get {
                return ResourceManager.GetString("DialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open Fui..
        /// </summary>
        internal static string DialogFailedToOpen {
            get {
                return ResourceManager.GetString("DialogFailedToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation.
        /// </summary>
        internal static string DialogInfo {
            get {
                return ResourceManager.GetString("DialogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve not saved the Fui yet. Do you exit this application?.
        /// </summary>
        internal static string DialogNotifySave {
            get {
                return ResourceManager.GetString("DialogNotifySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Fui.
        /// </summary>
        internal static string DialogOpenFui {
            get {
                return ResourceManager.GetString("DialogOpenFui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace image.
        /// </summary>
        internal static string DialogReplaceImage {
            get {
                return ResourceManager.GetString("DialogReplaceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all images.
        /// </summary>
        internal static string DialogSaveAllImages {
            get {
                return ResourceManager.GetString("DialogSaveAllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Fui! ({0}).
        /// </summary>
        internal static string DialogSavedFui {
            get {
                return ResourceManager.GetString("DialogSavedFui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Fui.
        /// </summary>
        internal static string DialogSaveFui {
            get {
                return ResourceManager.GetString("DialogSaveFui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image.
        /// </summary>
        internal static string DialogSaveImage {
            get {
                return ResourceManager.GetString("DialogSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save selected images.
        /// </summary>
        internal static string DialogSaveSelectedImages {
            get {
                return ResourceManager.GetString("DialogSaveSelectedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image first, please..
        /// </summary>
        internal static string DialogSelectImage {
            get {
                return ResourceManager.GetString("DialogSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string DialogWarning {
            get {
                return ResourceManager.GetString("DialogWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FUI_EnforcerLogo {
            get {
                object obj = ResourceManager.GetObject("FUI_EnforcerLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
